# Generated by Django 5.1.6 on 2025-02-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading_text", models.CharField(max_length=100)),
                ("heading_underline_text", models.CharField(max_length=100)),
                ("heading_description", models.TextField()),
            ],
        ),
    ]
