# Generated by Django 5.1.6 on 2025-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heropage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading_text_1", models.CharField(max_length=100)),
                ("heading_underline_text_1", models.CharField(max_length=100)),
                ("heading_description_1", models.TextField()),
                ("heading_text_2", models.CharField(max_length=100)),
                ("heading_underline_text_2", models.CharField(max_length=100)),
                ("heading_description_2", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
