# Generated by Django 5.1.6 on 2025-02-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_pagetitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_about", models.TextField()),
                ("about_list_1", models.CharField(max_length=255)),
                ("about_list_2", models.CharField(max_length=255)),
                ("about_list_3", models.CharField(max_length=255)),
                ("long_about", models.TextField()),
            ],
        ),
    ]
