# Generated by Django 5.1.6 on 2025-02-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_whatoffered"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("who_you_are", models.CharField(max_length=25)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=1,
                    ),
                ),
                ("testimony", models.TextField()),
                ("user_image", models.ImageField(upload_to="Testimonials")),
            ],
        ),
    ]
