# Generated by Django 5.1.6 on 2025-02-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="testimony",
            field=models.CharField(max_length=255),
        ),
    ]
