# Generated by Django 5.1.6 on 2025-02-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="audio_files/")),
                ("file_cover", models.ImageField(upload_to="Audio")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
