# Generated by Django 5.1.6 on 2025-02-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_audiofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="genre",
            field=models.CharField(
                choices=[("Gospel", "gospel"), ("Afro", "Afro")],
                default="Gospel",
                max_length=255,
            ),
        ),
    ]
