# Generated by Django 5.1.6 on 2025-02-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_audiofile_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="genre",
        ),
    ]
