# Generated by Django 5.1.6 on 2025-02-08 09:11

import app.models
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_audiofile_file_cover_alter_audiofile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file_cover',
            field=cloudinary.models.CloudinaryField(default='none', max_length=255, validators=[app.models.validate_image_file], verbose_name='image'),
            preserve_default=False,
        ),
    ]
