# Generated by Django 5.1.6 on 2025-02-10 19:35

import app.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_audiofile_file_alter_audiofile_file_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="file",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[app.models.validate_audio_file],
                verbose_name="audio",
            ),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="file_cover",
            field=cloudinary.models.CloudinaryField(
                max_length=255,
                validators=[app.models.validate_image_file],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="testimony",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="who_you_are",
            field=models.CharField(max_length=50),
        ),
    ]
